name: Quarto Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - run: |
          quarto render
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
